// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iso6976_calc
Rcpp::List iso6976_calc(Rcpp::NumericVector x, Rcpp::NumericVector u_x, Rcpp::NumericMatrix r_x, double t1, double t2, double p2, double k);
RcppExport SEXP _ISO6976_2016_iso6976_calc(SEXP xSEXP, SEXP u_xSEXP, SEXP r_xSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP p2SEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type u_x(u_xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r_x(r_xSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(iso6976_calc(x, u_x, r_x, t1, t2, p2, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ISO6976_2016_iso6976_calc", (DL_FUNC) &_ISO6976_2016_iso6976_calc, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ISO6976_2016(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
