# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate all ISO 6976:2016 properties and their uncertainties
#'
#' @param x       Numeric vector of length 60: mole fractions [mol/mol]
#' @param u_x     Numeric vector of length 60: standard uncertainties
#' @param r_x     Numeric matrix 60x60: correlation matrix
#' @param t1      Combustion temperature [°C]: 0, 15, 15.55, 20, or 25
#' @param t2      Volume reference temperature [°C]: 0, 15, 15.55, or 20
#' @param p2      Reference pressure [kPa]: 90–110
#' @param k       Coverage factor (default 1)
#' @return Named list of properties and uncertainties
iso6976_calc <- function(x, u_x, r_x, t1, t2, p2, k = 1.0) {
    .Call(`_ISO6976_2016_iso6976_calc`, x, u_x, r_x, t1, t2, p2, k)
}

